### ISSUE TITLE
Error installing Homebridge on macOS

### ISSUE THREAD

**Issue by lorenzofiamingo** [homebridge/homebridge#2729] opened 2020-11-25 18:00 UTC
**Describe The Bug:**
I just runned the second command in macOS installation guide.

**To Reproduce:**
Run the first and then the second command in macOS installation guide.

**Logs:**

```
sudo hb-service install
/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/axios/lib/cancel/Cancel.js:13
Cancel.prototype.toString = function toString() {
                          ^

TypeError: Cannot assign to read only property 'toString' of object '#<Cancel>'
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/axios/lib/cancel/Cancel.js:13:27)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/axios/lib/axios.js:40:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
```

**Homebridge Config:**

not present

**Environment:**

* **Node.js Version**: v13.8.0
* **NPM Version**: 6.14.9
* **Homebridge Version**:  1.1.6
* **Operating System**: macOS 11.0.1

**Comment by rlust** [comment] 2020-11-25 18:10
Same issue here. I cannot install hb-service.
Same error message.

**Comment by cullensanderson1** [comment] 2020-11-25 18:10
Hello, I just experneced the same thins. 
Node.js version v14.15.0
NPM Version 6.14.8
MacOS version 11.0.1

**Comment by Thazzril** [comment] 2020-11-25 18:16
Same issue on Windows 10 and Ubuntu 20.10

**Comment by MattHardwick34** [comment] 2020-11-25 18:42
Same issue on latest Raspian.

**Comment by blare78** [comment] 2020-11-25 18:43
Same issue, cannot install HB Service. Also doesn't create config.json file
Node.js: 15.3.0
NPM 7.0.14
MacOS: 10.15.5

**Comment by GrantLogan** [comment] 2020-11-25 18:53
Problem appears to be an issue with the latest version of dependency axios

Get homebridge back online today, by rolling back to 0.19.2.  sudo npm uninstall axios; sudo npm install axios@'0.19.2'

**Comment by oznu** [comment] 2020-11-26 01:22
This seems to be caused by an outage or issue elsewhere on the internet  / npm registry - whatever it was seems to have been resolved now.

For those impacted please run the following commands to repair your installation:

macOS:

```
npm cache clean --force
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
sudo hb-service rebuild
```

Linux:

```
sudo npm cache clean --force
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

Windows:

```
npm cache clean --force
npm uninstall -g homebridge-config-ui-x
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by oznu** [comment] 2020-11-26 04:54
Closing as several people have confirmed the issue is no longer occurring and we have an open issue for the same thing over on the Homebridge UI repo.

The timing for the failed installs / updates coincides with the AWS outage this morning, so the current thought is it some services such a npm were impacted for users in that region.

https://github.com/oznu/homebridge-config-ui-x/issues/969

**Closed** 2020-11-26 04:54 UTC
Labels: bug
