### ISSUE TITLE
Upgrade guide for Ubuntu #2

### ISSUE THREAD

**Issue by CRDunne** [homebridge/homebridge#2807] opened 2021-02-14 08:48 UTC
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment] 2021-02-14 09:28
Duplicate of https://github.com/homebridge/homebridge/issues/2804

**Closed by oznu** 2021-02-14 09:28 UTC
Labels: question
