### ISSUE TITLE
FIXED - All Devices - No Response

### ISSUE THREAD

**Issue by coryabooth** [homebridge/homebridge#3582] opened 2024-03-28 17:33 UTC
### Current Situation

Lastnight 3/27/2024 10pm CST - I noticed that none of my devices hosted by HomeBridge show as responsive in Apple home.
Devices with direct connection (Ecobee) and devices with a different bridge (RATGD and Scrypted) do still show and are responsive.

The Accessories tab in HomeBridge does show all my devices and they are controllable:
![image](https://github.com/homebridge/homebridge/assets/5266177/9d862622-798d-4f68-8a58-c84311c9a16a)

However, on the Home App - none of the devices show as "Responsive"
![image](https://github.com/homebridge/homebridge/assets/5266177/e991e524-c460-4e43-a049-e7f83f189d1e)

I have had this configuration - with no changes - for over a year now...
This just suddenly happened with no traceable reason...

I have five plugins - none of the devices exposed by these plugins are responsive in HomeKit - but they are in HomeBridge.

### Logs

```markdown
28/03/2024, 09:53:23] [Smartthings] Received events for Water Softener Alert
[28/03/2024, 09:53:23] [Smartthings] Event for Water Softener Alert:main - 73
[28/03/2024, 09:53:23] [Smartthings] Event updating temperature measurement for Water Softener Alert to 73
[28/03/2024, 09:53:23] [Smartthings] Posting request to web hook
[28/03/2024, 09:54:00] [homebridge-mobilelink] Logged in to MobileLink API.
[28/03/2024, 09:54:02] [homebridge-mobilelink] Discovered 1 generators using the MobileLink API.
[28/03/2024, 09:54:02] [homebridge-mobilelink] UUID:  - Generator Status: {"apparatusId":772390,"serialNumber":"3011641172","name":"Home","type":0,"localizedAddress":"","materialDescription":null,"heroImageUrl":"https://gpsprodmobilelink.blob.core.windows.net/apparatusimage/G0070422.jpg","apparatusStatus":1,"isConnected":true,"isConnecting":false,"showWarning":false,"weather":{"temperature":{"value":41,"unit":"F","unitType":18},"iconCode":1},"preferredDealerName":"SONS OF THUNDER","preferredDealerPhone":"5732864333","preferredDealerEmail":"","isDealerManaged":false,"isDealerUnmonitored":false,"modelNumber":"G0070422","panelId":"21","properties":[{"name":"Subscriptions/apparatuses/772390/SubscriptionsPremium","value":{"type":2,"status":1,"isLegacy":false,"isDunning":false},"type":2},{"name":"Device","value":{"deviceId":"","deviceType":"wifi","signalStrength":"68%","batteryLevel":null,"status":"Online","networkType":"wifi"},"type":3}],"values":null,"provisioned":"2022-09-21T15:08:34.6894429Z"}
[28/03/2024, 09:54:02] [homebridge-mobilelink] Updating existing accessory: Home
[28/03/2024, 09:54:48] [Smartthings] Received response from webhook {"timeout":true,"events":[]}
[28/03/2024, 09:54:48] [Smartthings] Posting request to web hook
[28/03/2024, 09:55:01] [homebridge-mobilelink] Logged in to MobileLink API.
[28/03/2024, 09:55:02] [homebridge-mobilelink] Discovered 1 generators using the MobileLink API.
```

### Configuration

```json
"bridge": {
        "name": "Homebridge 1DED",
        "username": "",
        "port": 51080,
        "pin": "",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "accessory": "HTTP-SWITCH",
            "name": "Hits 1",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Wake Up",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Upstairs",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "80s on 8",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "The Message",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "BPM",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Y2K",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Stop Music",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Apple Hits",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Pandora Hits",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Pandora Country",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Apple Country",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Hair Nation",
            "switchType": "stateless",
            "timeout": 10,
            "onUrl": ""
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Smartthings",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "",
            "WebhookToken": ",
            "GarageDoorMaxPoll": 0,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 0,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 0,
            "ExposeHumiditySensorForAirConditioners": false,
            "OptionalModeForAirConditioners": "None",
            "IgnoreDevices": [
                "Office Ecobee",
                "Closet Ecobee",
                "Master Ecobee",
                "Living Thermostat",
                "Basement Thermostat",
                "Kids Ecobee",
                "Guest Ecobee",
                "Garage Ecobee"
            ],
            "_bridge": {
                "username": "",
                "port": 52810
            },
            "platform": "HomeBridgeSmartThings"
        },
        {
            "username": "",
            "password": "",
            "discoverFrequency": 60000,
            "_bridge": {
                "username": "",
                "port": 30057
            },
            "platform": "MobileLink"
        },
        {
            "name": "Audio Upstairs",
            "host": "192.168.1.188",
            "port": "10006",
            "zones": [
                {
                    "zone_1": "Audio Garage",
                    "zone_2": "Audio Kitchen",
                    "zone_3": "Audio Living",
                    "zone_4": "Audio Upper",
                    "zone_5": "Audio Master",
                    "zone_6": "Audio Master Bath"
                }
            ],
            "inputs": [
                {
                    "source_1": "Rock",
                    "source_2": "Country",
                    "source_3": "Wave",
                    "source_4": "Pop",
                    "source_5": "Alexa",
                    "source_6": "Scanner"
                }
            ],
            "_bridge": {
                "username": "0E:39:68:18:48:D3",
                "port": 33002
            },
            "platform": "homebridge-htd-mca66"
        },
        {
            "name": "Audio Downstairs",
            "host": "192.168.1.187",
            "port": "10006",
            "zones": [
                {
                    "zone_1": "Audio Kalyssa",
                    "zone_2": "Audio Lower",
                    "zone_3": "Audio Guest",
                    "zone_4": "Audio Family",
                    "zone_5": "Audio Office",
                    "zone_6": "Audio Guest Bath"
                }
            ],
            "inputs": [
                {
                    "source_1": "Rock",
                    "source_2": "Country",
                    "source_3": "Wave",
                    "source_4": "Pop",
                    "source_5": "Alexa",
                    "source_6": "Scanner"
                }
            ],
            "platform": "homebridge-htd-mca66",
            "_bridge": {
                "username": "",
                "port": 40300
            }
        },
        {
            "token": "",
            "_bridge": {
                "username": "",
                "port": 43593
            },
            "platform": "Delta-VoiceIQ"
        }
    ],
    "disabledPlugins": [
        "homebridge-myq"
    ]
}
```

### Environment

Homebridge UI Version

4.55.1

Homebridge Version

1.7.0

Node.js Version

20.12.0

Operating System

Official Homebridge Raspberry Pi Image

Environment Info

None

Raspberry Pi Model

Raspberry Pi 4 B

### Process Supervisor

hb-service

**Comment by bwp91** [comment] 2024-04-01 18:53
What was the fix? Could help users reading this in the future 😀

Also if fixed please could you close the issue?

**Comment by bsy0318** [comment] 2024-04-03 00:32
I'm having the same problem. I opened the 51182 port from the firewall because I suspected a network issue, but it still shows 'no response'.

### Environment
**Homebridge UI Version**
v4.56.0

**Homebridge Version**
v1.7.0

**Node.js Version**
v18.19.0

**Operating System**

- Ubuntu Jammy (22.04.3 LTS)
- Official Homebridge repository

**Process Supervisor**
hb-service

### LOG
```
[4/3/2024, 9:04:57 AM] Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-gsh/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:631:28)
    at ClientRequest.emit (node:events:517:28)
    at Socket.emitRequestTimeout (node:_http_client:847:9)
    at Object.onceWrapper (node:events:631:28)
    at Socket.emit (node:events:529:35)
    at Socket._onTimeout (node:net:598:8)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[4/3/2024, 9:04:57 AM] Got SIGTERM, shutting down Homebridge...
2024-04-03T00:04:57.082Z hapHttpClient Disconnected from server 192.168.0.38:51182 undefined
2024-04-03T00:04:57.082Z hapNodeJSClient HAPevent events Reregister { server: '192.168.0.38:51182', deviceID: undefined }
[4/3/2024, 9:04:57 AM] Error: socket hang up
    at connResetException (node:internal/errors:720:14)
    at Socket.socketOnEnd (node:_http_client:525:23)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[4/3/2024, 9:04:57 AM] Error: socket hang up
    at connResetException (node:internal/errors:720:14)
    at Socket.socketOnEnd (node:_http_client:525:23)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[4/3/2024, 9:04:59 AM] Error: connect ECONNREFUSED 192.168.0.38:51182
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
[4/3/2024, 9:05:00 AM] [Google Smart Home] Received QUERY intent
```

**Comment by bsy0318** [comment] 2024-04-03 02:17
Problem solved.
In my case, it was a problem caused by some IoT Device not responding.
If you are experiencing the same error, please check if the IoT devices are responding correctly.

**Comment by coryabooth** [comment] 2024-04-03 02:27
Sorry.  There seems to be a few anomolies still.  I did a full power pull on the HomeBridge Pi and got all my ZWave devices back online.  But I do still have a few issues lingering. 

My RATGD will not respond even though I am able to reflash and reimport into HomeKit...  Once loaded into HomeKit it returns to "No Response"

My Scrypted bridge suddenly stopped working for remote camera viewing in HomeKit - local viewing its fine.  But once on LTE the camera feeds fail.  

I have several feeler questions out there but Im not sure where to turn given the sporadicness of the issues...

**Closed as completed** 2024-04-03 02:28 UTC
Labels: question

**Comment by coryabooth** [comment] 2024-04-04 04:39
To fully fix my issues I had to:

Disable IGMP Snooping
Disable Multicast and Broadcast Control
