### ISSUE TITLE
latest version 1.6.0 cause stuck in starting... issue in Synology 

### ISSUE THREAD

**Issue by lu9999** [homebridge/homebridge#3285] opened 2022-12-10 19:20 UTC
### Analysis

I tried the 1.6.0, and the 2.0.0 beta both had the same issue; there is no error in the log. but homebridge status is in "Starting..." forever, and I am not able to connect to the home app

After downgrading to 1.5.1, the homebrdige runs fine without any problems.

I am running my homebridge in my Synology NAS with latest system.

### Expected Behavior

The newer version should support Snology

### Steps To Reproduce

mentioned above

### Logs

```markdown
Log did not show any errors
```

### Configuration

```json
Snology
```

### Environment

- OS:Snology
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by SMGvideo** [comment] 2022-12-14 16:30
Seconded. Having the exact same problem.

**Comment by SMGvideo** [comment] 2022-12-14 16:33
> ### Analysis
> I tried the 1.6.0, and the 2.0.0 beta both had the same issue; there is no error in the log. but homebridge status is in "Starting..." forever, and I am not able to connect to the home app
> 
> After downgrading to 1.5.1, the homebrdige runs fine without any problems.

How did you manage to downgrade to 1.5.1?

**Comment by lu9999** [comment] 2022-12-14 18:29
Go to the web gui of Snology, go to the homebridge app, so on the top, click the version number, then choose the version you want

**Comment by lu9999** [comment] 2022-12-14 18:30
> > ### Analysis
> > I tried the 1.6.0, and the 2.0.0 beta both had the same issue; there is no error in the log. but homebridge status is in "Starting..." forever, and I am not able to connect to the home app
> > After downgrading to 1.5.1, the homebrdige runs fine without any problems.
> 
> How did you manage to downgrade to 1.5.1?

Go to the web gui of Snology, go to the homebridge app, so on the top, click the version number, then choose the version you want

**Comment by olivergruber** [comment] 2022-12-14 19:26
I have the same problem with 1.6.0, and downgrading to 1.5.1 fixes it. I have it running on Synology DSM version 7.1 Update 4.

This line is showing up in the logs (twice):
`Could not create mDNS advertisement. The HAP-Server won't be discoverable: Error: No such interface found`

**Comment by ebaauw** [comment] 2022-12-14 21:36
> I have the same problem with 1.6.0

@olivergruber, I doubt it, as the OP claims there are no errors in the log.  This error message indicates an issue with the underlying HAP-NodeJS v0.11.0, see https://github.com/homebridge/HAP-NodeJS/issues/993.

**Comment by olivergruber** [comment] 2022-12-14 22:04
> @olivergruber, I doubt it, as the OP claims there are no errors in the log. Your error message indicates an issue with the underlying HAP-NodeJS v0.11.0, see [homebridge/HAP-NodeJS#993](https://github.com/homebridge/HAP-NodeJS/issues/993).

You are right, I missed that OP explicitly stated that they saw no errors.

**Comment by tiramipseudonym** [comment] 2022-12-14 23:12
Same issue here. Running DSM 7.1.1 update 1 on a DS218j. No errors in the log.

**Comment by kmans** [comment] 2022-12-15 16:25
Also seeing this issue on Synology DSM 7.1

**Comment by rlieving** [comment] 2022-12-18 16:22
Seeing the same issue here. Downgrading to 1.5.1 resolved my issue as well.

**Comment by Caesar113** [comment] 2022-12-19 06:44
Same issue here. No error in the log, but stuck on starting forever. Changed the mDNS Advertiser from Avahi to Bonjour HAP and restarted the service and then it started without issue. Seems to be some sort of regression with Avahi on Synology introduced in 1.6.

**Comment by mcontreras** [comment] 2022-12-20 09:53
Same problem. Downgraded to 1.5.1 and problem fixed. Something is wrong with 1.6.0 build for Synology

**Comment by dfleck99** [comment] 2022-12-23 05:30
Same issue as everyone else.  Stuck on starting.  Changed to Bonjour Hap, restarted and ‘starting’ issue was resolved.

**Comment by konstantinbo** [comment] 2023-01-06 20:59
The problem is also present currently on my Synology DS918 with DSM 7.1.1-42962 Update 3

**Comment by Tulpe84** [comment] 2023-01-08 11:13
Exactly the same problem. I went back to version 1.5.1. With this everything runs without problems.

**Comment by AechLyons** [comment] 2023-02-08 19:38
Go to settings in homebridge and change the mdns advertiser from whatever it is (mine was defaulted to avahi) to ciao and restart. 
Worked for me

**Comment by giampablo** [comment] 2023-02-14 11:36
Problem solved for me, too. 
Going back to version 1.5.1 everything was running fine, upgrading to 1.6.0 the issue "starting..." appeared again. Went to settings, changed the mdns advertiser from "avahi" to "ciao", restarted. Now version 1.6.0 runs without problems.

**Comment by rlieving** [comment] 2023-02-14 12:18
Yes. This worked for me as well! Thank you.

**Comment by olivergruber** [comment] 2023-02-14 12:21
I changed it to Bonjour HAP, which also made it to work again.

**Comment by robwheatley** [comment] 2023-03-12 18:50
I have the same issue on a new DS120j
Solved (I guess at least for now) by switching to "ciao" as others have mentioned. I think that avahi is more efficient, so it would be good to be able to switch back at some point in the future when this is sorted.

**Comment by ITKern-JonasKern** [comment] 2023-04-03 17:12
I have found a solution without downgrade.
Go to Homebridge web interface -> ... -> Homebridge Settings -> mDNS Advertiser, change from Avahi to Bonjour HAP.

**Comment by Supereg** [comment] 2023-04-30 18:10
This issue was fixed in the latest v1.6.0 release.

**Closed by Supereg** 2023-04-30 18:10 UTC
Labels: bug
