### ISSUE TITLE
Siri "wasn't able to find anything like that this time"

### ISSUE THREAD

**Issue by Jefronty** [homebridge/homebridge#2165] opened 2019-02-26 16:02 UTC
### Pre Steps
activate Siri, say command

### Expected Behavior

Execute command
### Current Behavior

Siri responds with "Sorry, I wasn't able to find anything like that this time"
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```
I've had homebridge for several months, maybe a year, and it used to work well with Siri.  Now it only works in the Home app or from the swipe-up UI.  Nothing I say to Siri ever works with my homebridge and this has been happening for the last couple of months.  I see my cachedAccessories file hasn't been modified since October, would it be safe to rename or delete that and restart homebridge?  Or do you have any other ideas why Siri won't control anything and yet everything works as expected when controlling on screen?

**Comment by iRayanKhan** [comment] 2019-02-27 05:18
Well, are you using a HomePod?

**Comment by Jefronty** [comment] 2019-02-28 03:02
no, the only apple device I have is an iPhone

**Comment by Jefronty** [comment] 2019-03-01 15:12
Some more info on this issue.  I added a new device to homebridge this week, a wifi thermostat (homebridge-tcc)  Siri works with the new device, but nothing else.  Everything else works perfectly in the Home app.
Would emptying the persist directory possibly help?

**Comment by hepcat72** [comment] 2019-03-24 19:13
I was having this problem this morning.  It was working yesterday.  None of the usual fixes for things not responding was working (i.e. turn airplane mode on/off, restart the phone, restart the RPi, restart the homebridge server).  Just like you, the buttons in the Home app worked, but Siri kept giving that response, which is not one I'd specifically seen before.

It was affecting both my and my wife's (who was invited to the home/room) iPhone 6s.

What finally worked was this (I don't know if *all* these steps are necessary):

1. Stop homebridge `pm2 stop homebridge`
2. Remove the persist directory (I moved it just in case: `cd .homebridge;mv persist ..`)
3. Start homebridge `pm2 start homebridge`
4. In the home app, hard-press an accessory, tap details, tap bridge, tap "Remove bridge from home"
5. Re-scan the QR code that's in the log by tailing the log (`tail -n 100 /home/pi/.pm2/logs/homebridge-out.log`) and tapping "Add Accessory" in the home app
6. Turn airplane mode on and back off

It then took me a few tries, but everything started working again via Siri.

The only thing that had changed between today and yesterday was I had added a breadboard to my RPi and installed some stuff to be able to control some 433Hhz RF transmitter/receiver chips.  That involved a few installs.  I had also changed the noobs setting to boot into Raspbian and created a couple aliases in my .profile.  Among other things, I had run an RF sniffer program and a program I wrote to control an LED.  The breadboard and the RF receiver are still connected.  I was about to start working on the transmitter when I discovered Siri wasn't working.

**Comment by Jefronty** [comment] 2019-03-26 18:26
Thanks @hepcat72 I'll give that a try.  I have tried deleting/moving the persist directory.  But I'll try the steps you listed.

**Comment by hepcat72** [comment] 2019-03-26 18:31
Incidentally, I don't know if you use pm2 to start/stop your homebridge server.  My guess is that those steps aren't necessary, but it will put the QR code at the bottom of your log.  However you usually start/stop homebridge is how you should do it.

**Comment by hepcat72** [comment] 2019-03-26 18:32
And I deleted my saved persist directory out of my home dir once I confirmed it was working again.

**Comment by hepcat72** [comment] 2019-04-01 01:52
Did that work for you? I just added a plugin called homebridge-commander and the one outlet I set it up to control refuses to work with Siri.  It works great in the Home app, but I still get the error you're getting.  I performed my trick above a few time and although it worked with my previous issue, it doesn't seem to fix this issue.

**Comment by gijoecool** [comment] 2019-04-05 23:29
I have a similar issue but it’s with the homebridge-openhab plugin that I’ve been using for years.

**Comment by Bi7** [comment] 2019-04-06 00:38
I have also had this issue. However I have had interesting results using the room name + device name PLUS descriptor (such as kitchen can lights vs kitchen can) in my Siri voice commands.  

I have also gotten lights turned off, albeit all of them by referring to the room name, as in kitchen lights off.

Seems like the requirements to identify a device have been tightened up. It would be nice to know exactly how though.

B

**Comment by joe248** [comment] 2019-04-23 12:08
I also just started having this issue.  Nothing has changed with my setup.  I can control everything within the Home app but Siri "wasn't able to find anything like that at this time" every time I ask her to do something.  Interestingly, if I say "turn on the office" it will turn on my office light, but "turn on the office light" doesn't work.  Seem's like this is a bug on Apple's end.

**Comment by Jefronty** [comment] 2019-04-25 18:38
I've tried deleting accessories and persist directories and that didn't resolve the issue.  I then also deleted the HomeBridge _bridge_ from the Home app and changed the `username` and `pin` values in the config before adding it again.  Siri still is not controlling most of my devices.  Maybe I'll try add scenes since @joe248 said that worked for him.

**Comment by unconnected** [comment] 2019-05-01 06:28
> I also just started having this issue.  Nothing has changed with my setup.  I can control everything within the Home app but Siri "wasn't able to find anything like that at this time" every time I ask her to do something.  Interestingly, if I say "turn on the office" it will turn on my office light, but "turn on the office light" doesn't work.  Seem's like this is a bug on Apple's end.

Yes it seems to be an Apple thing. Normally I was able to say 'Turn on speakers', but now I've to say: 'Turn on the speakers switch'. Also with light switches, previously I could say 'Turn on <name>', now I've got to say 'Turn on <name> light'. Maybe I can make shortcuts with siri shortcuts to make things simple again :P

**Comment by joe248** [comment] 2019-05-07 19:03
Just wanted to update that this issue started happening again for me about a week ago.  Not sure what to do because constantly deleting my persist and cachedAccessories and re-adding everything isn't viable.

**Comment by Tiger519** [comment] 2019-05-24 13:24
@joe248 I just started having the same issue, but the fix came in @unconnected's solution. I have a cmd switch to turn on my receiver. I used to be able to say "Turn on the Airplay Input" but now I have to say "Turn on the Airplay Input switch". This only seems to be affecting my Homebridge devices, as I can still say "turn on the China Cabinet" which is a native Homekit switch and it finds it fine.

If I had to guess I'd say this isn't Homebridge specifically but all hubs since I found other people complaining of the same issue with Hue and other hubs. Siri is now requiring more information to find the specific device.

The weirdest thing to me is that Siri is clearly recognizing to device because it is capitalizing the name (i.e. it displays my speech as Airplay Input or Floods Toggle instead of airplay input or floods toggle). Yet it still won't work with out saying "switch" or "lock" or whatever device I'm trying to control. Really frustrating since this is a big step backwards in language understanding capabilities, even if it is (for me at least) only an issue for things through Homebridge.

**Comment by hepcat72** [comment] 2019-05-24 13:35
> @joe248 I just started having the same issue, but the fix came in @unconnected's solution. I have a cmd switch to turn on my receiver. I used to be able to say "Turn on the Airplay Input" but now I have to say "Turn on the Airplay Input switch". This only seems to be affecting my Homebridge devices, as I can still say "turn on the China Cabinet" which is a native Homekit switch and it finds it fine.
> 
> If I had to guess I'd say this isn't Homebridge specifically but all hubs since I found other people complaining of the same issue with Hue and other hubs. Siri is now requiring more information to find the specific device.
> 
> The weirdest thing to me is that Siri is clearly recognizing to device because it is capitalizing the name (i.e. it displays my speech as Airplay Input or Floods Toggle instead of airplay input or floods toggle). Yet it still won't work with out saying "switch" or "lock" or whatever device I'm trying to control. Really frustrating since this is a big step backwards in language understanding capabilities, even if it is (for me at least) only an issue for things through Homebridge.

I have an iPhone 4s that I keep plugged in and treat it like a smart speaker.  I noticed that I can tell it "turn on (or off) the lights", but my iPhone 6s wants me to say "turn on (or off) the lights outlet".  However, one time, I forgot and left off the "outlet" on the command to the 6s... and it worked!  Subsequent tries did not work - I had to specify "outlet".

Lately, Siri has been complaining that she tried but couldn't execute my command.  Sometimes the device does turn on or off.  Sometimes, it doesn't.  In both cases, Siri doesn't think it worked.  Sometimes, I can issue the command a second time and it will work.  Other times, it doesn't matter how many times I issue the command... it never works!  But in those cases, I can go to the home app and use the button and that always seems to work.

I think the problem may be Siri.  Siri recently forgot who my dad was and then when I fixed that, I would say "call my dad mobile" (as I always do), and Siri would ask "Which phone number for...".  Then, when I tapped "mobile", she would ask me again in a never ending loop...  I have a screen recording of that behavior.

So in my opinion, Siri has Alzheimer's.  She's pretty fragile.

**Comment by migabc** [comment] 2019-05-24 13:55
I've started to have the same issue since iOS 12.2.
Before it would understand the abreviated comand frase example "Turn off the FAN" but now I have to specify the exact device name and the room were it's located "turn off the HRV FAN in the basement" and I only have that one FAN

**Comment by joe248** [comment] 2019-05-24 13:59
I agree - it's very weird that Siri clearly recognizes my devices (because she capitalizes them as you mentioned) but she refuses to control them without using very precise language.  I also agree that the problem is most likely Siri, however, it's also strange that nuking my Homebridge / Homekit setup and starting from scratch does allow things to work the way they used to for some brief period of time.

**Comment by joshstrange** [comment] 2019-06-14 04:11
Just ran into this issue, I can control most things just fine with "Turn on/off X" but my new lock will only work if I saw "Lock/Unlock Front Room Front Door" but if I just say "Lock/Unlock Front Door" it will do the "wasn't able to find anything like that this time". Very frustrating, I really don't want to re-setup all my devices in all my rooms but I might try that tomorrow.

**Comment by gijoecool** [comment] 2019-06-14 11:51
I found this solution and it seems to work for me: https://discussions.apple.com/thread/250239027

**Comment by joe248** [comment] 2019-06-14 12:08
@gijoecool thanks for posting this.  I just renamed one of my switches, used Siri to control the switch under the new name, then renamed it back.  The problem appears to be fixed now for all of my devices, at least for the time being.

**Comment by joshstrange** [comment] 2019-06-14 12:30
@gijoecool Interesting find! I was able to rename mine to “Entrance Door” (from Front Door) and Siri started working but as soon as I renamed it back to Front Door I had the same issue. It makes me assume this is a “Siri” issue not a “HomeBridge” issue. That said I hope this thread stays open so we can discuss fixes here (much better than Apple Forums).

Also in case it helps anyone I just uses scenes called “Lock Door” and “Unlock Door” as a work around for right now (my door is the only thing experiencing this issue). This is far from an ideal solution but I thought I’d throw it out there.

**Comment by hepcat72** [comment] 2019-06-14 12:55
For me, the problem comes and goes over time. I discovered this by accident by forgetting to add “outlet”. I agree that this seems to be an issue with Siri/iOS.

**Comment by gijoecool** [comment] 2019-06-14 12:57
Yeah, this is definitely a Siri issue. I switched away from Homebridge with hopes of resolving this issue, but it’s followed me to Home Assistant. Hopefully it gets fixed in iOS 13.

**Comment by Jefronty** [comment] 2019-06-19 17:16
Odd that Siri understands what I say according to the speech to text on screen, even showing device names as they are in "Home," and was previously able to process the commands, but seemingly out of the blue stopped.

**Comment by hepcat72** [comment] 2019-06-25 17:13
FYI, I’ve been getting this error a lot lately. This morning, I changed the room name that a switch was assigned to and it started being able to control the “space heater” whereas before, I had to say “space heater switch”.

**Comment by hepcat72** [comment] 2019-07-02 13:42
Perhaps we should find a forum where we can talk about the issues with Siri?  This morning, Siri couldn’t find anything like my garage door. I made a screen recording of it in action. Eventually, I removed the garage door from the “room” it was in (named “back yard”) and created a copy of the room. When I put it in the new room, Siri worked.

https://www.dropbox.com/s/cswd4sq1tapg0ma/IMG_2633.TRIM.MOV?dl=0

**Comment by requiem240sx** [comment] 2019-08-31 14:10
I'm simply using wemo switch on homekit (no homebridge at all) yet. Which leads me to believe it is not a homebridge issue at all.  It happened to me the same way, just out of no where, I was not able to use siri, homekit app still worked fine though. 
I think it started roughly after a device updated its firmware. 

I simply re-named the device to something else, and it worked.  Then re-named it back and it was working fine after that.

**Comment by migabc** [comment] 2019-09-06 08:59
> I also just started having this issue. Nothing has changed with my setup. I can control everything within the Home app but Siri "wasn't able to find anything like that at this time" every time I ask her to do something. Interestingly, if I say "turn on the office" it will turn on my office light, but "turn on the office light" doesn't work. Seem's like this is a bug on Apple's end.
> 
> Edit: I just deleted my persist directory and cachedAccessories file. I then re-added Homebridge and all 30 of my accessories, which was a pain, but Siri control is working correctly now.

This "Siri not understanding some of my homekit accessories" is happening for me on all my IOS devices (iPhones and iPads) but not on the macOS (Siri on my iMac understands my command perfectly) - This is strange as I use the same apple ID across all my Apple devices and the Home app on all devices works fines as well.

I'm reluctant to delete my persist directory and cachedAccessories file as I have over 100 accessories across multiple Homebridges. Re-adding all my Homebridge accessories will be a real pain :-(
Anyway, since the issue does not occur on the macOS maybe it's an iOS bug and probably not related at all with homebridge

**Comment by migabc** [comment] 2019-09-06 09:10
I restarted my Apple TV 4 (which is configured as the Homekit hub for remote access) and it fixed the issue. :-)
I would never have guessed that it was the Apple TV all along.
This is really strange since this issue was occurring on my local network and only on iOS devices.
Anyway, I'm happy to say that the solution was very simple after all
Go figure ;-)

P.S. I guess this is an Apple Homekit bug and not a Homebridge issue

**Comment by brettohland** [comment] 2019-12-31 00:23
Something that might be helpful to others with this issue: I had to delete my entire house and re-create it in order for Siri to start to recognize my accessories again.

**Comment by Airyck** [comment] 2020-02-10 02:07
Try renaming the devices in Homekit to something different. Verify that it works again and name it back. Worked for me.

**Comment by hepcat72** [comment] 2020-02-10 14:07
Sure, that can work once, but it will start happening again at some point.

**Comment by setBoolean** [comment] 2020-02-28 15:42
> Try renaming the devices in Homekit to something different. Verify that it works again and name it back. Worked for me.

Renaming the whole Home also fixes the issue, and you don't need to rename every single device.

**Comment by donavanbecker** [comment] 2020-03-16 22:30
Sounds like a HomeKit Naming issue, closing issue.

**Closed by donavanbecker** 2020-03-16 22:30 UTC
