### ISSUE TITLE
Automations / Scriptable actions

### ISSUE THREAD

**Issue by GitFun4All** [homebridge/homebridge#3728] opened 2024-11-05 22:56 UTC
### Current Situation

Lacks support for actions / triggers / scripts

### Proposed Change

Include an API? or other methods of controlling home bridge accessories programatically, either internally or externally.

### Additional Context

1st of all, thank you for home bridge! I've been using it for years on various devices and configs (hw / VM / Qemu + Mac / RPi) and it's been mostly awesome. There are a few things (hue lights for example) where I use homeassistant as an alternative for automation / scripting etc. that I'd love to dump for home bridge if it supported actions / scripts etc.

Anyway, just my 2cs. Thanks again, keep up the good work!

**Comment by GitFun4All** [comment] 2024-11-05 22:58
Sorry, didn't see the other request that almost identical ;-(

**Comment by NorthernMan54** [comment] 2024-11-06 04:29
Duplicate of https://github.com/homebridge/homebridge/issues/3727

**Closed as completed by NorthernMan54** 2024-11-06 04:29 UTC
Labels: enhancement
