### ISSUE TITLE
npm update Removes Packages ... and downgrades UI?

### ISSUE THREAD

**Issue by arrmo** [homebridge/homebridge#3434] opened 2023-09-16 02:21 UTC
### Analysis

Very odd, but if I do a "normal" `npm` update on my Linux system
```
sudo npm install npm@latest
```

I find that after this, some plugins are often missing (e.g. Smartthings), and the UI and/or Homebridge server are often older then as well. I admit, not sure why updating `npm` would cause Homebridge issues like this.

### Expected Behavior

Update `npm`, Homebridge works as normal

### Steps To Reproduce

As above, just update `npm`

### Logs

```markdown
I can, NP! Just not sure what to provide here.
```

### Configuration

```json
For example, the portion for a plugin the often goes missing,
        {
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "XXXXX",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 20,
            "ExposeHumiditySensorForAirConditioners": false,
            "OptionalModeForAirConditioners": "None",
            "_bridge": {
                "username": "XXXXX",
                "port": 51125
            },
            "platform": "HomeBridgeSmartThings"
        },
```

### Environment

- OS: Ubuntu 22.04.3 LTS
- Software: 1.6.1
- Node: v18.16.0
- npm: 9.6.6

### Process Supervisor

systemd

**Comment by NorthernMan54** [comment] 2023-09-16 13:25
Depending on the directory you run `npm install` from and options you use it can have these types of impacts.  It is recommended to use the supplied command to update both node and npm to avoid these issues

[`sudo hb-service update-node`](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#updating)

**Comment by NorthernMan54** [comment] 2023-09-16 13:35
Also duplicate of https://github.com/homebridge/homebridge/issues/3352

**Closed by NorthernMan54** 2023-09-16 13:35 UTC
Labels: bug

**Comment by arrmo** [comment] 2023-09-16 16:30
> Depending on the directory you run `npm install` from and options you use it can have these types of impacts. It is recommended to use the supplied command to update both node and npm to avoid these issues
> 
> [`sudo hb-service update-node`](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#updating)

Makes sense - sort of 🤣. Just a routine update of npm (part of the system) seems to cause this - so don't let the system update it?

Thanks!
