### ISSUE TITLE
[Homebridge UI] Restore backup failed: zlib: unexpected end of file when trying to restore a backup on new HB instance on new machine.

### ISSUE THREAD

**Issue by sapireli** [homebridge/homebridge#3514] opened 2023-12-18 08:18 UTC
### Analysis

Backups created in homebridge-config-ui-x.

The error is the same always: "Restore backup failed: zlib: unexpected end of file"

Testing was done on a raspi running debian bookworm image of dietpi.

The backup comes in at 6.3mb compressed. It can be expanded and there is nothing wrong with the archive.

Upon closer inspection: there is a large hidden ".npm" folder inside the backup. This folder is a relatively large sub-folder -> _cacache/content-v2/sha512/ -> which contains over 100 two letter folders. Removing this folder and gzipping allows the backup file to be successfuly uploaded but then the terminal window reports the following error: "Error: Uploaded file is not a valid Homebridge Backup Archive."

### Expected Behavior

Should be able to restore from backup

### Steps To Reproduce

tried this on debian bookwork, and debian bullseye.

### Logs

```markdown
NA
```

### Configuration

```json
NA
```

### Environment

- OS: debian bookworm
- Software: homebridge latest 1.7.0
- Node: 	v20.10.0
- npm: dont rem

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment] 2023-12-18 20:10
Duplicate of https://github.com/homebridge/homebridge-config-ui-x/issues/1856

**Closed as completed by NorthernMan54** 2023-12-18 20:10 UTC
Labels: bug
