### ISSUE TITLE
Homebridge doest start after update

### ISSUE THREAD

**Issue by bojomojo** [homebridge/homebridge#2727] opened 2020-11-25 17:04 UTC
## See https://github.com/homebridge/homebridge/issues/2727#issuecomment-734019638

---

After last homebridge ui update, the following error happend
![44F76829-46CC-4A9A-A8D1-2040D88F4A79](https://user-images.githubusercontent.com/62281574/100259560-a2c67d00-2f48-11eb-820e-b44b3b919175.png)

**Comment by lagos1380** [comment] 2020-11-25 17:41
Experiencing the same issue.

**Comment by Thazzril** [comment] 2020-11-25 18:17
same issue as new installation

**Comment by Toolhead** [comment] 2020-11-25 18:51
Same here.

**Comment by bojomojo** [comment] 2020-11-25 20:39
As mentioned in other issues around here. Resetting to older version works. 
Try
Sudo npm -g uninstall homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
Then
Sudo hb-service restart

Worked for me

**Comment by tmacxx004** [comment] 2020-11-25 21:41
> As mentioned in other issues around here. Resetting to older version works.
> Try
> Sudo npm -g uninstall homebridge-config-ui-x
> sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> Then
> Sudo hb-service restart
> 
> Worked for me. This shall unblock us till we get a final fix

Any clue why it would say command not found?

**Comment by bojomojo** [comment] 2020-11-25 21:44
> > As mentioned in other issues around here. Resetting to older version works.
> > Try
> > Sudo npm -g uninstall homebridge-config-ui-x
> > sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> > Then
> > Sudo hb-service restart
> > Worked for me. This shall unblock us till we get a final fix
> 
> Any clue why it would say command not found?

Which command?

**Comment by tmacxx004** [comment] 2020-11-25 22:10
> > > As mentioned in other issues around here. Resetting to older version works.
> > > Try
> > > Sudo npm -g uninstall homebridge-config-ui-x
> > > sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> > > Then
> > > Sudo hb-service restart
> > > Worked for me. This shall unblock us till we get a final fix
> > 
> > 
> > Any clue why it would say command not found?
> 
> Which command?

Sudo npm -g uninstall homebridge-config-ui-x

When I try to install without uninstalling it said invalid segmentation.

**Comment by bojomojo** [comment] 2020-11-25 22:21
> > > > As mentioned in other issues around here. Resetting to older version works.
> > > > Try
> > > > Sudo npm -g uninstall homebridge-config-ui-x
> > > > sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> > > > Then
> > > > Sudo hb-service restart
> > > > Worked for me. This shall unblock us till we get a final fix
> > > 
> > > 
> > > Any clue why it would say command not found?
> > 
> > 
> > Which command?
> 
> Sudo npm -g uninstall homebridge-config-ui-x
> 
> When I try to install without uninstalling it said invalid segmentation.

Can you paste the error?

**Comment by tmacxx004** [comment] 2020-11-25 22:50
![ED25FB72-174A-4301-9EB9-58ACBDE4B937](https://user-images.githubusercontent.com/33605710/100289382-58d89980-2f3e-11eb-9227-154bd35871c5.jpeg)

**Comment by tmacxx004** [comment] 2020-11-25 22:51
> > > > > As mentioned in other issues around here. Resetting to older version works.
> > > > > Try
> > > > > Sudo npm -g uninstall homebridge-config-ui-x
> > > > > sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> > > > > Then
> > > > > Sudo hb-service restart
> > > > > Worked for me. This shall unblock us till we get a final fix
> > > > 
> > > > 
> > > > Any clue why it would say command not found?
> > > 
> > > 
> > > Which command?
> > 
> > 
> > Sudo npm -g uninstall homebridge-config-ui-x
> > When I try to install without uninstalling it said invalid segmentation.
> 
> Can you paste the error?

![EB0BF33B-C4CA-4D38-B92B-F0B3D281D558](https://user-images.githubusercontent.com/33605710/100289408-6beb6980-2f3e-11eb-8635-0daeec02939a.jpeg)

**Comment by emvxl** [comment] 2020-11-25 23:13
> > > > > > As mentioned in other issues around here. Resetting to older version works.
> > > > > > Try
> > > > > > Sudo npm -g uninstall homebridge-config-ui-x
> > > > > > sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x@4.32.0
> > > > > > Then
> > > > > > Sudo hb-service restart
> > > > > > Worked for me. This shall unblock us till we get a final fix
> > > > > 
> > > > > 
> > > > > Any clue why it would say command not found?
> > > > 
> > > > 
> > > > Which command?
> > > 
> > > 
> > > Sudo npm -g uninstall homebridge-config-ui-x
> > > When I try to install without uninstalling it said invalid segmentation.


It maybe the uninstall command. The install command has -g after the install. It maybe the same in the uninstall command.

**Comment by oznu** [comment] 2020-11-26 01:21
This seems to be caused by an outage or issue elsewhere on the internet  / npm registry - whatever it was seems to have been resolved now.

For those impacted please run the following commands to repair your installation:

macOS:

```
npm cache clean --force
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
sudo hb-service rebuild
```

Linux:

```
sudo npm cache clean --force
sudo npm uninstall -g homebridge-config-ui-x
sudo npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

Windows:

```
npm cache clean --force
npm uninstall -g homebridge-config-ui-x
npm install -g --unsafe-perm homebridge-config-ui-x@latest
```

**Comment by tmacxx004** [comment] 2020-11-26 01:27
The 

> npm cache clean --force

What if we’re using the Homebridge Rasp image? When I ssh into @pi and run those commands I get this error.
![Uploading 213BC433-096D-4BD4-9A7E-CC39EE4FE0DD.png…]()

**Comment by oznu** [comment] 2020-11-26 01:31
@tmacxx004 

what does `node -v` print out?

**Comment by tmacxx004** [comment] 2020-11-26 01:36
> @tmacxx004
> 
> what does `node -v` and `npm -v` print out?
> 
> Have you made any other changes like trying to change the Node.js version?

I haven’t made any changes aside from updates through the UI.

![F0975460-7964-4C32-AB63-202DFF7D3A31](https://user-images.githubusercontent.com/33605710/100297958-77965a80-2f55-11eb-915b-21088df15778.png)

**Comment by oznu** [comment] 2020-11-26 01:38
@tmacxx004 run `sudo hb-config` and select the first option to `Update Node.js`. Then try run those commands again.

**Comment by tmacxx004** [comment] 2020-11-26 01:41
> @tmacxx004 run `sudo hb-config` and select the first option to `Update Node.js`. Then try run those commands again.

It’s already the latest version

**Comment by oznu** [comment] 2020-11-26 01:43
Is that what it says?

**Comment by oznu** [comment] 2020-11-26 01:45
The tool checks the current node version by running `node -v` - if it can't determine it should just reinstall.

Can you update the `hb-config` tool using the second last option and try again just to make sure?

**Comment by tmacxx004** [comment] 2020-11-26 01:55
> The tool checks the current node version by running `node -v` - if it can't determine it should just reinstall.
> 
> Can you update the `hb-config` tool using the second last option and try again just to make sure?

I just updated everything and it’s still not working. I’ll just reimage it... was hoping to avoid that

**Comment by oznu** [comment] 2020-11-26 01:57
Probably a good idea. If `node -v` isn't working then there is likely a bigger problem than what this issue is about.

**Comment by oznu** [comment] 2020-11-26 04:55
Closing as several people have confirmed the issue is no longer occurring and we have an open issue for the same thing over on the Homebridge UI repo.

The timing for the failed installs / updates coincides with the AWS outage this morning, so the current thought is it some services such a npm were impacted for users in that region.

https://github.com/oznu/homebridge-config-ui-x/issues/969

**Closed by oznu** 2020-11-26 04:55 UTC
