### ISSUE TITLE
Getting error when update Node.js is attempted

### ISSUE THREAD

**Issue by CBP980** [homebridge/homebridge#3347] opened 2023-04-03 17:51 UTC
### Analysis

I have Homebridge running on DSM 7 

I'm trying to update Node.js as when I go to update plugins, it complains that I should be at newer version (v16.19.1) than where I am (v16.16.0).  

This is interesting as the Synology itself is running 18.12.0-0005.
Node.js was updated via Synology update process for other apps to version.

I see that 16.x should work fine for now, that 18.x is supported as well....
Node.js 16.x until September 2023
Node.js 18.x until April 2025

However, when I go to update Node.js, I get an error:
homebridge@indy:/volume1/homebridge $ hb-service update-node 
ℹ Updating Node.js from v16.16.0 to v18.15.0...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.

This perhaps is just an issue with Synology and versioning, but since Synology did the update to get Node.js to 18, it seems odd that the output is saying it is unsupported.

### Expected Behavior

I'd expect that Homebridge would see / notice that Node.js had been updated to 18.12.  

Other than that, I wouldn't expect an unsupported error when I attempt to do the update to get Homebridge to see the update.  

### Steps To Reproduce

I ssh to Synology
sudo to root
issue hb-service update-node 

also tried:
hb-service update-node 18.12
(same error)

### Logs

```markdown
hb-service update-node
ℹ Updating Node.js from v16.16.0 to v18.15.0...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.


hb-service update-node 18.12
ℹ Installing Node.js v18.12.1 over v16.16.0...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.
```

### Configuration

```json
nothing of note for this section
```

### Environment

- OS:  Synology DSM 
- Software:  1.6.0
- Node:  v16.16.0

### Process Supervisor

hb-service

### Additional Context

I am able to get Node.js to update to 16.19, but would like to move to 18 and be consistent.  

hb-service update-node 16.19
ℹ Installing Node.js v16.19.1 over v16.16.0...
ℹ Target: /volume1/@appstore/homebridge/app
✔ Download complete.
✔ Cleaned up npm at at /volume1/@appstore/homebridge/app/lib/node_modules/npm
✔ Installed Node.js v16.19.1
⚠ Please restart Homebridge for the changes to take effect.

**Comment by MadDogOfHell** [comment] 2023-04-12 21:18
Hi :) I have the same issue and HUE plugin says, that it needs node 18.15 to run. I've checked the synology and it has ver 18.12 installed. Can't install the higher version on synology. HB see 16.16 version. 
sudo hb-service update-node I get the error described ny CBP980.

**Comment by gabors** [comment] 2023-04-14 07:25
Same issue. @oznu pls help

**Comment by gleep52** [comment] 2023-04-15 18:25
I just updated my node to 18.16 successfully - perhaps it was an 18.15 issue?  Just posting to see if that was the case... sorry I'm not more help.

**Comment by gabors** [comment] 2023-04-16 00:45
I am still getting this error:

`Homebridge Terminal for Synology DSM

Node.js Version: v17.9.1
Node.js Path: /var/packages/homebridge/target/app/bin/node
Plugin Path: /volume1/homebridge/node_modules

Update Node.js: hb-service update-node

Install Plugin: hb-service add homebridge-plugin-name
Remove Plugin: hb-service remove homebridge-plugin-name

homebridge@Bond:/volume1/homebridge $ hb-service update-node
ℹ Updating Node.js from v17.9.1 to v18.16.0...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.
homebridge@Bond:/volume1/homebridge $ 
`

**Comment by gleep52** [comment] 2023-04-16 01:44
My apologies - I didn’t see the synology NAS had a limit - I’m using a raspberry pi.  Your error shows that the OS of synology isn’t yet compatible with node 18 - you would need to reach out to Synology to see what they can do for that limitation I imagine.

**Comment by gabors** [comment] 2023-04-16 02:00
No worries. Synology had support for node js 18 since 2022. From what I read. 
homebridge has its own copy afaik

**Comment by NorthernMan54** [comment] 2023-04-16 13:21
I believe the Synology homebridge package is located here - https://github.com/oznu/homebridge-syno-spk

This issue should be raised there.

**Comment by FezVrasta** [comment] 2023-05-06 08:28
Complete instructions to upgrade to Node 18

https://github.com/homebridge/homebridge-syno-spk/issues/120#issuecomment-1537086792

**Comment by pbutler6163** [comment] 2023-05-16 14:59
Tried this on my updated 7.2-64551 DSM. Now Homebridge wont load. I reverted the coped source and it still wont load. I may have to uninstall re-install homebridge to fix

**Comment by skmzwanke** [comment] 2023-05-28 21:25
Oznu docker on Synology DSM 7.2. Getting same error when trying to update to node js 18.

**Comment by jwebbstevens** [comment] 2023-06-23 17:22
same error here. 

"Updating Node.js from v16.16.0 to v18.16.1...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later."

Running DSM 7.1.1-42962 Update 6 on a DS1520+. Using [homebridge-syno-spk](https://github.com/homebridge/homebridge-syno-spk) version 3.0.9.

**Comment by NorthernMan54** [comment] 2023-06-27 14:09
Duplicate of #3301

**Closed by NorthernMan54** 2023-06-27 14:09 UTC
Labels: bug
