### ISSUE TITLE
All devices unresponsive only when new Apple TV acting as home hub

### ISSUE THREAD

**Issue by twynne** [homebridge/homebridge#3331] opened 2023-03-11 13:31 UTC
### Current Situation

Have been having this issue for several weeks now, and have finally definitively narrowed it to a specific scenario.  Unfortunately struggling to find a way around it, so thought I'd check if others are impacted.

Firstly the environment:

Homebridge 1.6.0 running on MacOS
Node.js v18.14.2
Most iOS/tvOS devices running latest beta - 16.4 I believe

Home has three devices capable of acting as homekit hub - an older 4k Apple TV, a new 4k Apple TV, and a homepod mini.

When the older apple tv or homepod mini are acting as the active hub, all homebridge devices work fine.  Annoyingly my home setup seems to prefer the newer apple tv to act as home hub.  Whenever that apple tv takes over, all homebridge devices become unresponsive.  As far as I'm aware there is no way to tell homekit NOT to use a certain device as hub, nor to set one as preferred.

I can temporarily resolve this by forcing the new apple tv offline until one of the other devices takes over, but it only lasts so long.

Firstly is anyone else seeing issues with homebridge when a new Apple TV 4k is acting as the hub?  Beyond that, is there any way that others are aware of to stop it acting as hub, or to tell homekit to prefer a different device as hub?

### Logs

```markdown
Not relevant
```

### Configuration

```json
Not relevant
```

### Environment

- OS: MacOS
- Software: Homebridge 1.6.0
- Node: 18.14.2
- npm: 9.5.0

### Process Supervisor

hb-service

**Comment by twynne** [comment] 2023-03-11 13:33
Should have added, both Apple TV's (old and new) are connected ethernet, as is the MacOS server running homebridge.  There is no wifi involved here.

**Comment by NorthernMan54** [comment] 2023-03-11 13:57
That's an interesting finding, which mDNS Advertiser are you using ?   And if you switch to the other, does it make a difference.

Also does your new ATV, have both IPV4 and IPV6 enabled ?  ( Not sure if there is an option for this )

**Comment by twynne** [comment] 2023-03-11 15:42
Ciao is enabled.

Looking at Apple TV itself, I don't see any options to manage ip4 Vs ip6.

**Comment by twynne** [comment] 2023-03-11 15:51
I can of course try changing the Advertiser, but won't know if it has any effect until the next time the new ATV becomes the hub... which is unfortunately completely random.  Do you think there's value in trying?  Any downside to the other advertiser?

**Comment by NorthernMan54** [comment] 2023-03-11 15:53
Ciao and Bonjour behave a little bit different, so it may make a difference, I personally find that Ciao works better but YMMV.

Typically unresponsive is caused by the mDNS messages not being received, and mDNS needs a simple flat network to work ( it is a local network broadcast protocol ).   Are all your ATV's plugged into the same switch?

If you swapped your ATV devices around, does it make a difference ?

Also I thought you could disable an ATV from being a home hub

![image](https://user-images.githubusercontent.com/19808920/224494223-4346f238-7aea-497d-b0aa-11fc0cc6e025.png)

**Comment by twynne** [comment] 2023-03-11 16:00
Weird... I don't even have that part of the menu appearing on mine!  I'll look again but was just in there twice and the menu ended at 'homekit' with no option to do anything 'hub' related.

To answer your question, it's all Unifi networking here and all of the rooms ultimately connect back to the same 'main' switch.  There are additional switches between the main and the apple tv, but that is the same with each of them.

I have since had one other thought.  The main (new) apple TV is the one that we actually use to watch media most often.  It so happens that I have a separate iTunes account (one US, one UK) which we often use to watch films.  I'm now wondering if it's failing to act as home hub when I swap apple TV to the US account.  Will take some more experimentation.

First I'm going to check if as you've shared it's possible to prevent it acting as hub, as that would solve either way.

**Comment by twynne** [comment] 2023-03-11 16:04
Ok, just checked.  I *definitely* don't have that 'home hub' menu section at all.  Any idea what enables it?

**Comment by NorthernMan54** [comment] 2023-03-11 16:14
If your switching iTunes account it is definitely the root cause of the issue, as HomeKit uses the iTunes account to share HomeKit information.

I'm thinking that if you switched your phone to the US account, you would see your home in HomeKit.

For the missing menu option, I have a second home created for testing homebridge called `Heisenberg` I'm wondering if that enabled the menu option.

A quick google found this from Apple, https://support.apple.com/en-ca/guide/tv/atvb0753b37d/tvos

Does it work in your setup ?

**Comment by twynne** [comment] 2023-03-11 16:25
My UK account is both the default on all tvOS devices, and the account used for homekit.    I might try setitng up a second home and see if that helps.

Also found this topic (https://discussions.apple.com/thread/250112648) which suggests there's a menu option beneath iCloud that allows the device to be 'disabled' as a home hub.  Again I don't have that option anywhere.  Not sure if it has since been moved or removed.  I've looked through all menus and can't locate it.

**Comment by twynne** [comment] 2023-03-11 16:48
> If your switching iTunes account it is definitely the root cause of the issue, as HomeKit uses the iTunes account to share HomeKit information.
> 
> 
> 
> I'm thinking that if you switched your phone to the US account, you would see your home in HomeKit.
> 
> 
> 
> For the missing menu option, I have a second home created for testing homebridge called `Heisenberg` I'm wondering if that enabled the menu option.
> 
> 
> 
> A quick google found this from Apple, https://support.apple.com/en-ca/guide/tv/atvb0753b37d/tvos
> 
> 
> 
> Does it work in your setup ?

Just reread that... It makes sense that switching accounts may be a cause. I which case you'd think that homekit would switch to another hub, but it doesn't. 

Best solution appears to be preventing the new Apple TV from acting as hub. Frustratingly I just can't see a way to do that.

**Comment by NorthernMan54** [comment] 2023-03-11 16:56
My ATV's are running the latest release....

As this is not a homebridge issue, can we close this ?

**Comment by twynne** [comment] 2023-03-11 17:02
Yes, save thank you for the help in any case. 😁

**Closed** 2023-03-11 17:03 UTC
Labels: question
