### ISSUE TITLE
Install Instructions: Unable to locate package homebridge

### ISSUE THREAD

**Issue by ryanholden8** [homebridge/homebridge#3407] opened 2023-07-29 21:26 UTC
### Analysis

Following the instructions to install results in a "Unable to locate package homebridge" error

### Expected Behavior

The install instructions works

### Steps To Reproduce

See logs for commands used

### Logs

```markdown
homebridge@homebridge:~$ curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null
[sudo] password for homebridge: 

homebridge@homebridge:~$ echo "deb [signed-by=/usr/share/keyrings/homebridge.gpg] https://repo.homebridge.io stable main" | sudo tee /etc/apt/sources.list.d/homebridge.list > /dev/null

homebridge@homebridge:~$ sudo apt-get update
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease                   
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease           
Get:4 https://repo.homebridge.io stable InRelease [3,242 B]             
Fetched 3,242 B in 4s (802 B/s)                   
Reading package lists... Done

homebridge@homebridge:~$ sudo apt-get install homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package homebridge
```

### Configuration

```json
Homebridge is not configured yet
```

### Environment

- OS: Fresh install of Debian (lsb_release -d Debian GNU/Linux 12 (bookworm))
- Software:
- Node: not installed
- npm: not installed

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment] 2023-07-30 23:41
We have not released a package for bookworm yet.

Duplicate of #3399

**Closed by NorthernMan54** 2023-07-30 23:41 UTC
Labels: bug

**Comment by karlhuther** [comment] 2024-01-22 23:34
> We have not released a package for bookworm yet.
> 
> Duplicate of #3399

Do we know when this will be released?

**Comment by NorthernMan54** [comment] 2024-01-23 00:32
Bookworm support was released in the fall

**Comment by karlhuther** [comment] 2024-01-23 16:21
I unfortunately received the same error as the original poster.

**Comment by karlhuther** [comment] 2024-01-23 16:23
I unfortunately have the same issue as the first post with the latest version of bookworm.

**Comment by NorthernMan54** [comment] 2024-01-24 00:49
Please redo these steps

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#installing-homebridge
