### ISSUE TITLE
v1.3.x - Notifications work only for a few minutes after opening and closing the Home App.

### ISSUE THREAD

**Issue by TheEngineerGuy** [homebridge/homebridge#2908] opened 2021-04-21 14:38 UTC
**Describe The Bug:**
Finally updated from 1.1.7 to 1.3.4, and all seemed to be well for the first use. But later realised that my notification for homebridge provisioned accessories are no longer working. So, I:

1. Opened the home app saw all accessories were still in there, and they accurately depicted the state.
2. Closed the home app, and opened my garage door, notifications worked.
3. Waited 30-40 minutes, opened the garage door again, notifications failed.
4. Made sure that interface for bridge is selected in Homebridge config.
5. Repeated test, same result.
6. Switched from Bonjour to CIAO
7. Repeated test, same result.
8. Reverted back to 1.1.7.
9. All is good again.

A couple of important points:
- Discovery for mDNS seems to be working correctly.
- My personal devices are on a separate VLAN from HB and IoT devices.
- Multicast forwarding is explicitly enabled between the VLANs.

[**Logs:**]

In the log below, first open and closed state were not notified on, but (after opening the home app and closing it) second open and second closed state were notified on.
```
[4/20/2021, 7:15:54 PM] [Garage Door] Garage Door: Opening.
[4/20/2021, 7:16:01 PM] [Garage Door] Garage Door: Open.
[4/20/2021, 7:17:35 PM] [Garage Door] Garage Door: Closing.
[4/20/2021, 7:17:45 PM] [Garage Door] Garage Door: Closed.
[4/20/2021, 8:01:57 PM] [Garage Door] Garage Door: Opening.
[4/20/2021, 8:02:07 PM] [Garage Door] Garage Door: Open.
[4/20/2021, 8:03:10 PM] [Garage Door] Garage Door: Closing.
[4/20/2021, 8:03:20 PM] [Garage Door] Garage Door: Closed.
```

**Homebridge Config:**

```json
{
    "mdns": {
        "interface": "xxx.xxx.xxx.xxx"
    },
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxxxx,
        "pin": "xxx-xx-xxx",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
```

**Environment:**

* **Node.js Version**: v15.12.0
* **NPM Version**: v7.7.6
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

Additionally, I ran PCAP 
- In notifications not working state and source & destination filters enabled. In 2 minutes only 1 packet transferred from HB to iPhone, a simple mDNS query.
- In notifications working state and source & destination filters enabled. In 2 minutes, over 200 packets communicated between HB and iPhone.
- This certainly points to the fact that HB actively stops sending notifications to devices after a certain period of time.

**Comment by TheEngineerGuy** [comment] 2021-04-21 18:41
Update: Switching to CIAO and then back to Bonjour, seems to make it work somehow. Maybe a different kind of bug here.

- Bonjour right out of the box fails, 
- Switch to ciao fails, 
- Switch back to bonjour works. 

Going strong for 2 hours now. I will update if I see any change.

**Comment by Supereg** [comment] 2021-04-24 11:18
Could you try to further debug the issue by enabling parts of the `HAP-NodeJS` debug logging,
specifically the loggers `HAP-NodeJS:EventedHTTPServer`, `HAP-NodeJS:EventedHTTPServer:Connection` and `HAP-NodeJS:Accessory`.
The first two capture connection behavior, opening and closing of connections, and additionally logs when event notifications are sent out.
The third one probably prints more information than needed, but it includes debug messages when clients enable or disable event notifications for a given characteristic.

The debuggers can be set via the `DEBUG` environment value (there is also a way to easily define them in config ui, in the homebridge settings). Each logger is separated by a comma.
E.g. a logger enabling all three `DEBUG=HAP-NodeJS:EventedHTTPServer,HAP-NodeJS:EventedHTTPServer:Connection,HAP-NodeJS:Accessory`


----


You talked about doing some wireshark captures. When you talk about "In 2 minutes, over 200 packets communicated between HB and iPhone", packets means any communication between the two? Or is this only talking about mDNS? Was this capture using bonjour or ciao advertiser?

**Comment by TheEngineerGuy** [comment] 2021-04-26 17:44
Thanks for looking into it @Supereg .

For packets, that would be all unicast communication between the two devices. The filter I had used was ```ip.addr==HomeBridgeIP && ip.addr==iPhoneIP```.

As for logging, I have enabled the loggers that you have suggested, and I will get some more info for you.

**Comment by TheEngineerGuy** [comment] 2021-04-27 22:01
On a side note, is there a reason why we are using ```ffff``` to denote IPv4 addresses, as if they are are IPv6 mapped IPv4 addresses, which they are not?

**Comment by TheEngineerGuy** [comment] 2021-05-06 14:47
Hi @Supereg haven't heard back in a while. Is there a beta version you would like me to test or anything else?

**Comment by TheEngineerGuy** [comment] 2021-05-17 15:17
Hey Guys, Just wanted to check if this issue is being looked into. Not expecting it to be fixed right away, but if atleast it is getting looked into I can understand that a future version will fix it.

@Supereg @oznu

**Comment by TheEngineerGuy** [comment] 2021-06-17 01:50
This shouldn't be stale, given that it hasn't been fixed.

**Comment by TheEngineerGuy** [comment] 2021-08-19 02:53
Not stale. Geez bot.. :)

**Comment by TheEngineerGuy** [comment] 2021-09-19 01:51
Not stale..

**Comment by TheEngineerGuy** [comment] 2021-11-11 14:56
Tested 1.3.6, issue is still there. Reverting back to 1.1.7.

**Comment by TheEngineerGuy** [comment] 2021-12-07 23:30
@Supereg I think it has been a while since we looked into this issue. Do we have any speculations around it?

**Comment by NorthernMan54** [comment] 2021-12-08 00:30
@TheEngineerGuy - I presume your issue occurs when your local ?

Looking at the config you shared, this is part of the challenge ( multiple networks when HomeKit assumes a flat network )

```
Discovery for mDNS seems to be working correctly.
My personal devices are on a separate VLAN from HB and IoT devices.
Multicast forwarding is explicitly enabled between the VLANs.
```

Event communication between homebridge and your iPhone uses a consistent TCP socket connection initiated by the client device ( your iPhone ) to homebridge, connecting to the HAP port. Please see section 6.8 of the HAP Specification for details.

If your using Wireshark to troubleshoot your network you should see a TCP socket opened from your iDevice to homebridge, and that socket stay open.  If the socket closes then that is the issue.

If you enable debug logging on homebridge for HAP-NodeJS:*, you should see lines like this shortly after start up.  These are the clients registering a socket for events. A single socket can be reused for multiple events

```
 HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.75] HTTP request: /characteristics +2ms
  HAP-NodeJS:HAPServer [AA:BB:CC:DD:EE:01] HAP Request: PUT /characteristics +3ms
  HAP-NodeJS:Accessory [Heisenberg 4534] Processing characteristic set: {"characteristics":[{"aid":15,"iid":16,"ev":true},{"aid":15,"iid":17,"ev":true}]} +3ms
  HAP-NodeJS:Accessory [::ffff:192.168.1.75] Registered Characteristic "Status Low Battery" on "Heisenberg 4534" for events +0ms
  HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.75] HTTP Response is finished +1ms
```

These are the consistent TCP sockets for events from my MacBook (.75) to my various iDevices.

```
netstat -an | grep 51826
tcp4       0      0  192.168.1.75.51826     192.168.1.69.61671     ESTABLISHED
tcp4       0      0  192.168.1.75.51826     192.168.1.73.51858     ESTABLISHED
tcp4       0      0  192.168.1.75.51826     192.168.1.71.49652     ESTABLISHED
tcp4       0      0  192.168.1.75.51826     192.168.1.27.53035     ESTABLISHED
tcp4       0      0  192.168.1.75.51826     192.168.1.75.62768     ESTABLISHED
```

**Comment by TheEngineerGuy** [comment] 2021-12-08 01:16
I haven't tested while remote, but I would resume that it will happen in both cases, because ATV (which is my Home Hub) will experience the same issue as it sits on the same network as my other iDevices.

I can see that sockets stay open on 1.1.7. But since this is a zero trust network with firewall in the middle, if a socket isn't used for some amount of time, the TCP session will be dropped by the firewall. I think we maybe onto something here.

Maybe that is what changed from 1.1.7 to 1.2.x and 1.3.x, is that hap reduced or eliminated its keep-alive packets in order to pursue reduction of chattiness. Is it possible to execute keep-alive on these sockets once every minute?

**Comment by NorthernMan54** [comment] 2021-12-08 01:22
The source is here, with this comment

https://github.com/homebridge/HAP-NodeJS/blob/03431b8f93137f4c969888a3d631f52da5b787b6/src/lib/util/eventedhttp.ts#L347

**Comment by TheEngineerGuy** [comment] 2021-12-08 01:23
Hmm... Wasn't this the case with 1.1.7 as well, or is this new?

**Comment by NorthernMan54** [comment] 2021-12-08 01:55
This change added the comment, which was a significant rewrite of the event handling logic

https://github.com/homebridge/HAP-NodeJS/commit/9a2fa34aa0ebf758004417db1bd143bb643fbefc

Your network design and firewall are the root cause of the issue here.  To remediate the issue you need to investigate adjusting the idle TCP socket settings on your firewall.

**Comment by TheEngineerGuy** [comment] 2021-12-08 02:00
It certainly may seem that way. But not root cause, firewall is doing what it is supposed to, which is not let stale session be open. I think this is a basic flaw in a TCP socket based application design which requires indefinite amount of session timeout. This application is not designed to be executed in a secure fashion is what I gather.

Not your fault, you are just following the specs, but definitely a fault of application coder not understanding core network security concepts as required by NIST.

Let me see what can be done.

**Comment by TheEngineerGuy** [comment] 2021-12-08 02:14
So what I have done now is, created an exception for TCP sessions to homebridge specifically only from trusted iDevices network to be up to a month long.

Let me run some tests and see what I can gather.

**Comment by Supereg** [comment] 2021-12-08 18:33
To provide some context how sockets are handled in HAP (e.g., also the open source HAP ADK).
As mentioned above, in the code and in the spec, the protocol specification requires that any sort of keep alive packets MUST NOT be used. As otherwise iDevices would be constantly waken up from sleep.
Consequentially, the HAP Server has no means to detect a dead socket anymore if the client isn't subscribed to any events which occurs regularly (normal requests are always initiated from the client side). Instead what HAP-NodeJS does, and what e.g. also the ADK does is to periodically clear out sockets based on time, once a given threshold is reached.
Typically, HomeKit devices are resource constrained and therefore, anyways, only have a fixed amount of parallel TCP streams they can support (HAP requires every device to support at least 8). The ADK closes the oldest sockets once this limit is reached.

> but definitely a fault of application coder not understanding core network security concepts as required by NIST.

I would honestly be interested in hearing the argument under which aspects or circumstances this has severe impact on security? Cause, I don't know about similar recommendations from e.g. the BSI.

**Closed** 2021-12-08 19:58 UTC
Labels: bug, pinned

**Comment by arkadicolson** [comment] 2021-12-09 10:23
Hi

From time to time I have the same issue. After reading this thread I'm unable to determine the exact solution for the issue. What exactly did solved you issue?

Br
Arkadi

**Comment by TheEngineerGuy** [comment] 2021-12-09 16:11
I updated TCP sessions timeouts from iDevices network to Homebridge device to be 32 days or 2,764,800 seconds.

Essentially, the firewall policy that allows this communication can be modified to provide a session TTL exception for just that policy. How you implement it will depend on which firewall you are using, but it should be available to you on most deep inspection firewalls. 

I would strongly recommend against implementing this massive session TTL across the board on your firewall, because with that you may just not have a firewall at all at that point.

I hope this helps.
