### ISSUE TITLE
possibly a minor package.json issue

### ISSUE THREAD

**Issue by jcdufourd** [homebridge/homebridge#3495] opened 2023-11-20 15:19 UTC
### Analysis

Here is an update message:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge@1.7.0',
npm WARN EBADENGINE   required: { node: '^18.15.0 || ^20.7.0' },
npm WARN EBADENGINE   current: { node: 'v21.2.0', npm: '10.2.4' }
npm WARN EBADENGINE }

This is wrong, even if just a warning, since node v21.2.0 is above v20.7.0

### Expected Behavior

expected behaviour is no warning

### Steps To Reproduce

update to 1.7.0 with node 21.2.0 (or any 21.*.* probably)

### Logs

```markdown
complete operation log is:
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-config-ui-x@4.52.3',
npm WARN EBADENGINE   required: { node: '^18 || ^20', homebridge: '^1.6.0' },
npm WARN EBADENGINE   current: { node: 'v21.2.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge@1.7.0',
npm WARN EBADENGINE   required: { node: '^18.15.0 || ^20.7.0' },
npm WARN EBADENGINE   current: { node: 'v21.2.0', npm: '10.2.4' }
npm WARN EBADENGINE }

changed 1 package in 3s

192 packages are looking for funding
  run `npm fund` for details
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 1D5B",
        "username": "0E:72:DF:DC:1D:5B",
        "port": 51053,
        "pin": "306-59-613",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "eveatmo platform",
            "ttl": 540,
            "extra_co2_sensor": false,
            "weatherstation": true,
            "airquality": false,
            "co2_alert_threshold": 1000,
            "log_info_msg": true,
            "auth": {
                "client_id": "xxx",
                "client_secret": "xxx",
                "grant_type": "refresh_token",
                "refresh_token": "xxx"
            },
            "platform": "eveatmo"
        },
        {
            "name": "Velux-Bridge",
            "username": "x",
            "password": "x",
            "platform": "Velux-Active"
        }
    ]
}
```

### Environment

- OS: MacOS Sonoma
- Software: 1.6.1
- Node: 21.2.0
- npm: 10.2.4

### Process Supervisor

hb-service

**Comment by grzegorz914** [comment] 2023-11-20 15:24
same for me

**Comment by bwp91** [comment] 2023-11-20 15:26
This is simply meant to be a reminder that Homebridge does not officially support odd versions of node.

See https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

It's not to say that Node 21 won't work with homebridge or the plugins you use, but a lot of plugins also follow the Homebridge convention of only supporting (currently) node 18 and 20.

**Comment by bwp91** [comment] 2023-11-20 15:28
The `'^18.15.0 || ^20.7.0'` means _be happy with 18.15.0 or any higher version of v18, and the same with v20 - so not 19 or 21_

**Comment by jsiegenthaler** [comment] 2023-11-22 06:16
From the Node website:
https://nodejs.org/en/about/previous-releases
Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. **Production applications should only use Active LTS or Maintenance LTS releases.**

This is therefore behaviour by design, and not a bug.  This issue should be closed.

**Comment by jsiegenthaler** [comment] 2023-11-22 06:18
This is behaviour by design, and not a bug. This issue should be closed.

**Closed as completed** 2023-11-22 13:34 UTC
Labels: bug
