### ISSUE TITLE
Homekit invitation not successful

### ISSUE THREAD

**Issue by Jeepmg** [homebridge/homebridge#3501] opened 2023-11-28 11:39 UTC
### Current Situation

Since November 1st, my wife has no longer been in my Homekit home and a new invitation has not been successful.

After hours spent with Apple support, all that's left is the Homebridge to test.

Could you send an invitation with up-to-date Apple IOS and Homebridge software and see if it succeeds on another iPhone?

### Logs

```markdown
In my Homekit app the invitation appears to have succeeded. In my wife's Homekit application, error message: invitation cannot be completed.
```

### Configuration

```json
Revision	: b03114
Model		: Raspberry Pi 4 Model B Rev 1.4

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
```

### Environment

node -v
v20.10.0

npm -v
10.2.3

homebridge, homebridge UI, Homebridge Z2M, Homebridge Tahoma : Latest current release.

### Process Supervisor

hb-service

### Additional Context

Thanks for your help, I don't know what to test anymore.

**Comment by JurgenLB** [comment] 2023-11-28 19:10
I don't think homebridge handels the invite, that's all apple Home.
But in the past when I mest-up the SD-card from my Pi running Homebridge, it was necessary to change the code from the Homebridge-config file to have homebridge reconnected to Homekit.

I hope you find a solution.

**Comment by jsiegenthaler** [comment] 2023-12-08 07:27
Invites to Apple Home is an Apple HomeKit function, and nothing to do with Homebridge

What you should do is:
1. Ensure both phones are on iOS 17.1.2, update as needed
2. Uninvite / remove your wife from Apple Home on your phone (as long as you are the Home admin)
3. Ensure no invites are pending. Ensure she has been removed
4. On you wife's phone, delete the Home app entirely
5. Restart both phones
6. On you phone, check in the Home app if any invites are pending. If so, cancel them again
7. Wait 30min for all systems to update and sync status (Apple Backend systems)
8. Install Home app on wife's phone
9. Invite her again - be patient, wait for the invite to appear

**Comment by jsiegenthaler** [comment] 2023-12-08 07:28
And of course, close this issue as the issue is not a Homebridge issue :)

**Comment by Jeepmg** [comment] 2023-12-08 15:16
> And of course, close this issue as the issue is not a Homebridge issue :)

**Closed as completed** 2023-12-08 15:15 UTC
Labels: question
