### ISSUE TITLE
Automations sometimes are not executed on latest beta

### ISSUE THREAD

**Issue by skywalker1979** [homebridge/homebridge#2733] opened 2020-11-29 15:13 UTC
Automations sometimes are lost (not executed) using the latest beta and 1.2.0 and > versions.

On 1.1.6 i never see lost automations.
Automations that are lost are different. Sometimes it's the heating not turning on, other times the blinds not closing at sunset or a light not switching on when i arrive home.
i tried a few betas and version from 1.2.0 onward and always see some problems.
So i went back to 1.1.6 and i'm having no problems whatsoever. (i would say more than 3 weeks.)
Problems have been seen with Apple TV 4k, as router, always update to latest os. (same for the ios device.)

```json
{
    "bridge": {
        "name": "Homebridge 18XX",
        "username": "0E:9D:98:xx:xx:xx",
        "port": 51311,
        "pin": "000-00-000"
    },
    "accessories": [
        {
            "name": "NAS",
            "ip": "192.168.3.78",
            "pingInterval": 45,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "mac": "00:1C:xx:xx:xx:xx",
            "wakeGraceTime": 90,
            "shutdownCommand": "sshpass -p 'password' ssh -oStrictHostKeyChecking=no -oHostKeyAlgorithms=+ssh-dss username@192.168.3.78 shutdown -p now",
            "shutdownGraceTime": 35,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        },
        {
            "accessory": "NetworkDevice",
            "name": "nas",
            "mac": "04:92:xx:xx:xx:xx",
            "ip": "192.168.3.77",
            "pingInterval": 30,
            "wakeGraceTime": 20,
            "shutdownGraceTime": 20,
            "shutdownCommand": "net rpc shutdown  --ipaddress 192.168.3.77 --user username%password"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "blue-grey",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Domoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "roomid": 0,
            "mqtt": true,
            "ssl": false,
            "dimFix": 0,
            "excludedDevices": [
                "45",
                "58",
                "70",
                "162",
                "185",
                "187",
                "70",
                "76",
                "79",
                "154",
                "169",
                "183",
                "187",
                "189",
                "190",
                "140",
                "76",
                "45",
                "70",
                "58",
                "162",
                "185",
                "187",
                "191",
                "192",
                "193",
                "192",
                "191",
                "201",
                "200",
                "199",
                "198",
                "211",
                "212",
                "209",
                "79",
                "87",
                "247",
                "248",
                "253",
                "196",
                "268",
                "140",
                "221",
                "189",
                "287",
                "190",
                "154",
                "249",
                "251",
                "216",
                "289",
                "213",
                "260",
                "188",
                "351",
                "270",
                "271"
            ],
            "platform": "eDomoticz"
        }
    ]
}


```

**Environment:**
Raspbian Buster.
Version Node.js | v12.18.3
Version NPM: v6.14.6
Homebridge 1.2.0 work ok, after not.
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service

**Comment by Supereg** [comment] 2020-11-29 16:05
When you say "lost". Do you mean they just don't execute or they are lost completely in the Home App (like you need to reconfigure them)?

**Comment by Supereg** [comment] 2020-11-29 16:12
Additionally: There were some advancements made with the latest 1.3.x beta. Could you try the latest beta release, namely homebridge 1.3.0-beta.28?

**Comment by skywalker1979** [comment] 2020-11-29 18:01
sorry....by "lost" i mean they are not executed.

**Comment by oznu** [comment] 2020-11-29 21:52
> do you want me to try beta 28?

Yes please 😄

**Comment by dkossman** [comment] 2020-11-29 22:16
I have the same issue- running homebridge 1.2.3 on Raspbian.  HomeKit automations to turn on and off homebridge accessories just don’t work.  In my case, the targets are Tuya-compatible switches and plugs.  I’m using the latest version of the homebridge-tuya plugin to control these locally.  If I set up similar automations on the Tuya app, those work fine.

**Comment by skywalker1979** [comment] 2020-11-29 23:58
ok...i installed it. I'll let you know in a few days. I hope the heating is going to switch on tomorrow morning! 🤣

**Comment by Supereg** [comment] 2020-11-30 00:05
> I hope the heating is going to switch on tomorrow morning!

classic people in smart home age 😂

**Comment by skywalker1979** [comment] 2020-12-03 19:28
have not seen it yet...even if it was there in beta~24.
mmh...i'll update to beta 30 and keep it going for a few more days.

**Comment by Supereg** [comment] 2020-12-03 19:38
@skywalker1979 so seems like it is fixed in beta 30? Is that what you are saying?

> Has there been a specific fix for this?

we'll yes. like not specifically for automations, but stability improvements to mdns advertising (which can be a cause of non executing automations).

**Comment by skywalker1979** [comment] 2020-12-03 19:46
i see.....it seems solved....if you want we can close it, and if i see it again i'll reopen... 👍 ....so happy! 😃

**Comment by Supereg** [comment] 2020-12-03 19:52
As the issue is called "Automations sometimes are not executed **on latest beta**" and the issue doesn't happen anymore on the **latest** beta, I would suggest to close it 😄 
In any case, we are about to announce some more widespread beta testing phase. So if there should be still any issues, we hope to catch it there.

Thanks in any case. Helps to be confident with the latest beta build.

**Closed by Supereg** 2020-12-03 19:52 UTC
Labels: beta, bug
